import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "./{components}/Nav";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ticket App",
  description: "Generated by AYY",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative flex flex-col h-screen max-h-screen">
          <Nav />

          <div
            aria-hidden="true"
            class="absolute -top-96 left-1/2 transform -translate-x-1/2 z-10"
          >
            <div class="bg-gradient-to-r from-violet-300/50 to-purple-100 blur-3xl w-[25rem] h-[44rem] rotate-[-60deg] transform -translate-x-[10rem] dark:from-violet-900/50 dark:to-purple-900"></div>
            <div class="bg-gradient-to-tl from-blue-50 via-blue-100 to-blue-50 blur-3xl w-[90rem] h-[50rem] rounded-fulls origin-top-left -rotate-12 -translate-x-[15rem] dark:from-indigo-900/70 dark:via-indigo-900/70 dark:to-blue-900/70"></div>
          </div>

          <div className="relative z-20 flex-grow overflow-y-auto text-default-text">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
